<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<div>

<?php echo $date;  ?>

<form action="logout" method="POST">

<input type="submit" name="logout" value="logout">

</form>

<h3>add product</h3>


<form action="/Product/addproduct" method="POST">
name<input type="text" name="name">
price<input type="text" name="price">

<input type="submit" name="add" value="add">

</form>
<div class="m-4">
<a href="/product/display"  class="btn btn-primary">product list</a>
</div>
</div>

    
</body>
</html>