<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->
    <title>Document</title>
</head>
<body>
<div class="container" >

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">price</th>
    
    </tr>
  </thead>
  <tbody>

  <?php
  
  $str="";
    for($i=0; $i<count($data); $i++) {

        // echo $data[$i]->name;
        $str.='<tr>
        <th scope="row">'.$data[$i]->product_id.'</th>
        <td>'.$data[$i]->name.'</td>
        <td>'.$data[$i]->price.'</td>
      </tr>';
    }

    echo $str;

?>

   
  </tbody>
</table>
 
<div>
    <a href="/login/loginuser"  class="btn btn-primary">addproduct</a>
</div>

</div>

    
</body>
</html>